### ISSUE TITLE
How to include 3rd party css/sass

### ISSUE THREAD

**Issue by bertvh** [fbrctr/fbrctr.github.io#12]
The docs describe how to include a js-module from node_modules, but what about styles/fonts/etc.?

I'm trying to include [bootstrap-material](http://fezvrasta.github.io/bootstrap-material-design/) as my base style.

**Comment by lukeaskew** [comment]
You can install bootstrap-material by installing via npm and including the main stylesheet in your sass file.

I like to include the `includePaths: './node_modules'` option in the `gulp-sass` task to make including sass dependencies from npm a little easier. It would make your import statement something like this:

```
@import 'bootstrap-material-design/sass/bootstrap-material-design';
```

For fonts, you'll need to write a `fonts` gulp task that pipes the fonts to the output folder for you.

**Comment by martijndewit** [comment]
I used https://www.npmjs.com/package/gulp-copy to copy my fonts from src to dist, because I had no need to render them again.
`
gulp.task('fontcopy', function() {
    gulp.src(config.src.fonts)
    .pipe(gulpCopy(config.dest + '/assets/toolkit/fonts', {prefix:4}));
});
`
Don't forget to run the task somewhere :)
