### ISSUE TITLE
Can't Import Project Style 

### ISSUE THREAD

**Issue by pcabrera83** [fbrctr/fbrctr.github.io#13]
I'm having a hard time inserting my projects stylesheet. I placed the style main.scss in default.html.

Here is the code for my projects personal style sheet. I placed the file 'main.scss' in /assets/toolkit/styles/main.css.

<link href="{{baseurl}}/assets/toolkit/styles/main.css" rel="stylesheet" type="text/css">

I also placed an image in the images folder of my toolkit. I tried calling up the images using
<img src="{{baseurl}}/src/assets/toolkit/images/test.jpg"/>
the images fails to load. 

// Gulp File Code 

// configuration
var config = {
    dev: gutil.env.dev,
    src: {
        scripts: {
            fabricator: './src/assets/fabricator/scripts/fabricator.js',
            toolkit: './src/assets/toolkit/scripts/toolkit.js'
        },
        styles: {
            fabricator: 'src/assets/fabricator/styles/fabricator.scss',
            toolkit: 'src/assets/toolkit/styles/toolkit.scss'
        },
        images: 'src/assets/toolkit/images/*_/_.jpg',
        views: 'src/toolkit/views/*.html'
    },
    dest: 'dist'
};

**Comment by lukeaskew** [comment]
Got this figured out via Gitter 👍

**Comment by pcabrera83** [comment]
Yes, you did. 💯  Thanks a bunch.
